/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Comment = IDL.Record({
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'authorName' : IDL.Text,
  'likes' : IDL.Nat,
  'publicationDate' : IDL.Text,
  'comments' : IDL.Vec(Comment),
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [Post], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'updatePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'authorName' : IDL.Text,
    'likes' : IDL.Nat,
    'publicationDate' : IDL.Text,
    'comments' : IDL.Vec(Comment),
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [Post], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'updatePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };